---
title: "Demographic, Social, Economic, and Housing Characteristics for Kingsport, TN"
author: "Paul Collins"
date: '`r format(Sys.Date(), "%m/%d/%Y")`'
output: 
  prettydoc::html_pretty:
    theme: cayman
bibliography: bibliography.bibtex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, include=FALSE}
packages <- c("acs", "tidyverse", "tidycensus", "tigris", "leaflet", "mapview", "tmap", "DT", "sf", "gganimate", "report")

lapply(packages, library, character.only = TRUE)


```

# Summary

blah blah asdfasdfasdfasdgasgd

```{r load data, include = FALSE, echo = FALSE}
  
  dp_table_variables_18 <- load_variables(2018, "acs5/profile", cache = TRUE)

  new_names_18 <- c("variable", "label", "concept")

  names(dp_table_variables_18) <- new_names_18
 
  ##may use 13 sometime for comparison so go ahead and load it in
  
  dp_table_variables_13 <- load_variables(2013, "acs5/profile", cache = TRUE)
  
  new_names_13 <- c("variable", "label", "concept")
  
  names(dp_table_variables_13) <- new_names_13

    
  Sullivan_dp02_2018 <- get_acs(geography = "tract", county = "Sullivan", state = "TN", table = "DP02", year = 2018, geometry = TRUE, cache = TRUE)
  
  Sullivan_dp03_2018 <- get_acs(geography = "tract", county = "Sullivan", state = "TN", table = "DP03", year = 2018, geometry = TRUE, cache = TRUE)
  
  Sullivan_dp04_2018 <- get_acs(geography = "tract", county = "Sullivan", state = "TN", table = "DP04", year = 2018, geometry = TRUE, cache = TRUE)
  
  Sullivan_dp05_2018 <- get_acs(geography = "tract", county = "Sullivan", state = "TN", table = "DP05", year = 2018, geometry = TRUE, cache = TRUE)
  
  Hawkins_dp02_2018 <- get_acs(geography = "tract", county = "Hawkins", state = "TN", table = "DP02", year = 2018, geometry = TRUE, cache = TRUE)
  
  Hawkins_dp03_2018 <- get_acs(geography = "tract", county = "Hawkins", state = "TN", table = "DP03", year = 2018, geometry = TRUE, cache = TRUE)
  
  Hawkins_dp04_2018 <- get_acs(geography = "tract", county = "Hawkins", state = "TN", table = "DP04", year = 2018, geometry = TRUE, cache = TRUE)
  
  Hawkins_dp05_2018 <- get_acs(geography = "tract", county = "Hawkins", state = "TN", table = "DP05", year = 2018, geometry = TRUE, cache = TRUE)
  
  Sullivan_dp02_18 <- inner_join(Sullivan_dp02_2018, dp_table_variables_18, by = "variable")
  
  Sullivan_dp03_18 <- inner_join(Sullivan_dp03_2018, dp_table_variables_18, by = "variable")
  
  Sullivan_dp04_18 <- inner_join(Sullivan_dp04_2018, dp_table_variables_18, by = "variable")
  
  Sullivan_dp05_18 <- inner_join(Sullivan_dp05_2018, dp_table_variables_18, by = "variable")
  
  Hawkins_dp02_18 <- inner_join(Hawkins_dp02_2018, dp_table_variables_18, by = "variable")
  
  Hawkins_dp03_18 <- inner_join(Hawkins_dp03_2018, dp_table_variables_18, by = "variable")
  
  Hawkins_dp04_18 <- inner_join(Hawkins_dp04_2018, dp_table_variables_18, by = "variable")
  
  Hawkins_dp05_18 <- inner_join(Hawkins_dp05_2018, dp_table_variables_18, by = "variable")
  
  
  Sullivan_data_profile <- rbind(Sullivan_dp02_18, Sullivan_dp03_18, Sullivan_dp04_18, Sullivan_dp05_18)
  
  Hawkins_data_profile <- rbind(Hawkins_dp02_18, Hawkins_dp03_18, Hawkins_dp04_18, Hawkins_dp05_18)
  
  combined_tract_dp_18 <- rbind(Sullivan_data_profile, Hawkins_data_profile)
  
  Sullivan_County_dp02_2018 <- get_acs(geography = "county", county = "Sullivan", state = "TN", table = "DP02", year = 2018, geometry = TRUE, cache = TRUE)
  
  Sullivan_County_dp03_2018 <- get_acs(geography = "county", county = "Sullivan", state = "TN", table = "DP03", year = 2018, geometry = TRUE, cache = TRUE)
  
  Sullivan_County_dp04_2018 <- get_acs(geography = "county", county = "Sullivan", state = "TN", table = "DP04", year = 2018, geometry = TRUE, cache = TRUE)
  
  Sullivan_County_dp05_2018 <- get_acs(geography = "county", county = "Sullivan", state = "TN", table = "DP05", year = 2018, geometry = TRUE, cache = TRUE)
  
  Hawkins_County_dp02_2018 <- get_acs(geography = "county", county = "Hawkins", state = "TN", table = "DP02", year = 2018, geometry = TRUE, cache = TRUE)
  
  Hawkins_County_dp03_2018 <- get_acs(geography = "county", county = "Hawkins", state = "TN", table = "DP03", year = 2018, geometry = TRUE, cache = TRUE)
  
  Hawkins_County_dp04_2018 <- get_acs(geography = "county", county = "Hawkins", state = "TN", table = "DP04", year = 2018, geometry = TRUE, cache = TRUE)
  
  Hawkins_County_dp05_2018 <- get_acs(geography = "county", county = "Hawkins", state = "TN", table = "DP05", year = 2018, geometry = TRUE, cache = TRUE)
  
  Sullivan_County_dp02_18 <- inner_join(Sullivan_County_dp02_2018, dp_table_variables_18, by = "variable")
  
  Sullivan_County_dp03_18 <- inner_join(Sullivan_County_dp03_2018, dp_table_variables_18, by = "variable")
  
  Sullivan_County_dp04_18 <- inner_join(Sullivan_County_dp04_2018, dp_table_variables_18, by = "variable")
  
  Sullivan_County_dp05_18 <- inner_join(Sullivan_County_dp05_2018, dp_table_variables_18, by = "variable")
  
  Hawkins_County_dp02_18 <- inner_join(Hawkins_County_dp02_2018, dp_table_variables_18, by = "variable")
  
  Hawkins_County_dp03_18 <- inner_join(Hawkins_County_dp03_2018, dp_table_variables_18, by = "variable")
  
  Hawkins_County_dp04_18 <- inner_join(Hawkins_County_dp04_2018, dp_table_variables_18, by = "variable")
  
  Hawkins_County_dp05_18 <- inner_join(Hawkins_County_dp05_2018, dp_table_variables_18, by = "variable")
  
  
  Sullivan_County_data_profile <- rbind(Sullivan_County_dp02_18, Sullivan_County_dp03_18, Sullivan_County_dp04_18, Sullivan_County_dp05_18)
  
  Hawkins_County_data_profile <- rbind(Hawkins_County_dp02_18, Hawkins_County_dp03_18, Hawkins_County_dp04_18, Hawkins_County_dp05_18)
  
  combined_county_dp_18 <- rbind(Sullivan_County_data_profile, Hawkins_County_data_profile)
  
  
#these are named wrong, the dataprofiles are for all tennessee school districts until if is filtered below as 
#kingsport data profile 
  
  kpt_dp02_2018 <- get_acs(geography = "school district (unified)",  state = "TN", table = "DP02", year = 2018, cache = TRUE)
  
  kpt_dp03_2018 <- get_acs(geography = "school district (unified)",  state = "TN", table = "DP03", year = 2018, cache = TRUE)
  
  kpt_dp04_2018 <- get_acs(geography = "school district (unified)",  state = "TN", table = "DP04", year = 2018, cache = TRUE)
  
  kpt_dp05_2018 <- get_acs(geography = "school district (unified)",  state = "TN", table = "DP05", year = 2018, cache = TRUE)
  
  kptcity_dp02_18 <- inner_join(kpt_dp02_2018, dp_table_variables_18, by = "variable")
  
  kptcity_dp03_18 <- inner_join(kpt_dp03_2018, dp_table_variables_18, by = "variable")
  
  kptcity_dp04_18 <- inner_join(kpt_dp04_2018, dp_table_variables_18, by = "variable")
  
  kptcity_dp05_18 <- inner_join(kpt_dp05_2018, dp_table_variables_18, by = "variable")
  
  tn_data_profile_18 <- rbind(kptcity_dp02_18, kptcity_dp03_18, kptcity_dp04_18, kptcity_dp05_18)
  
  districts <- school_districts(state = "TN", type = "unified", refresh = TRUE)
  
  districts <- st_as_sf(districts)
  
  kpt_18 <- districts %>%
    filter(NAME == "Kingsport City School District")

  kpt_data_profile_18 <- tn_data_profile_18 %>%
    filter(NAME == "Kingsport City School District, Tennessee")

```

# Age Demographics


```{r data for data tables, echo = FALSE}
  
  age_vars_18 <- c("DP05_0001",  "DP05_0005",  "DP05_0006",  "DP05_0007",  "DP05_0008",  "DP05_0009",
                "DP05_0010",  "DP05_0011",  "DP05_0012",  "DP05_0013",  "DP05_0014", 
                "DP05_0015",  "DP05_0016",  "DP05_0017",  "DP05_0018",  "DP05_0021",  "DP05_0024")
  
  age_vars_percent_18 <- c("DP05_0001P", "DP05_0005P",  "DP05_0006P", "DP05_0007P",  "DP05_0008P", 
                        "DP05_0009P",  "DP05_0010P",  "DP05_0011P", "DP05_0012P",  "DP05_0013P",  "DP05_0014P",
                        "DP05_0015P", "DP05_0016P",  "DP05_0017P",  "DP05_0018P",  "DP05_0021P", 
                        "DP05_0024P")
  
  age_col_dt_names_reg <- c("Total Population",  
                             "Age Under 5 Years", "Age 5-9 Years", "Age 10-14 Years",  "Age 15-19 Years", 
                             "Age 20-24 Years",  "Age 25-34 Years",  "Age 35-44 Years",  
                             "Age 45-54 Years",  "Age 55-59 Years",  "Age 60-64 Years", 
                             "Age 65-74 Years",  "Age 75-84 Years",  "Age 85+ Years",  
                             "Median Age", "Age 18+ Years",  "Age 65+ Years")
  
  age_col_dt_names_percent <- c("Total Population Percentage","Age Under 5 Years Percentage","Age 5-9 Years Percentage", "Age 10-14 Years Percentage","Age 15-19 Years Percentage", "Age 20-24 Years Percentage",
                                 "Age 25-34 Years Percentage", "Age 35-44 Years Percentage", "Age 45-54 Years Percentage", "Age 55-59 Years Percentage", "Age 60-64 Years Percentage", "Age 65-74 Years Percentage",
                                 "Age 75-84 Years Percentage","Age 85+ Years Percentage","Median Age Percentage", "Age 18+ Years Percentage", "Age 65+ Years Percentage" )
  
  
  dt_age_tract_counts <- combined_tract_dp_18 %>%
    filter(variable %in% age_vars_18)
  
  dt_age_county_counts <- combined_county_dp_18 %>%
    filter(variable %in% age_vars_18)
  
  dt_age_tract_percent <- combined_tract_dp_18 %>%
    filter(variable %in% age_vars_percent_18)
  
  dt_age_county_percent <- combined_county_dp_18 %>%
    filter(variable %in% age_vars_percent_18)
  
  dt_age_kpt_counts_18 <- kpt_data_profile_18 %>%
    filter(variable %in% age_vars_18)
  
  dt_age_kpt_percent_18 <- kpt_data_profile_18 %>%
    filter(variable %in% age_vars_percent_18)
  
    age_tract_df <- cbind(age_col_dt_names_reg, dt_age_tract_counts, dt_age_tract_percent)
  
  age_tract_dt <- age_tract_df[,c(1,3,5,6,12,13)]
  
  age_dt <- st_set_geometry(age_tract_dt, NULL)
  
  age_dt_names <- c("Age Group", "Census Tract", "Count Estimate", "Count Margin of Error", "Percent of Total Population", "Percent Margin of Error")
  
  names(age_dt) <- age_dt_names
  
  age_data_table <- datatable(age_dt)  

  
  #county data table
  
  dt_age_county_counts <- combined_county_dp_18 %>%
    filter(variable %in% age_vars_18)
  
  dt_age_county_percent <- combined_county_dp_18 %>%
    filter(variable %in% age_vars_percent_18)
  
  age_county_df <- cbind(age_col_dt_names_reg, dt_age_county_counts, dt_age_county_percent)
  
  age_county_dt <- age_county_df[,c(1,3,5,6,12,13)]
  
  age_county_dt <- st_set_geometry(age_county_dt, NULL)
  
  age_dt_county_names <- c("Age Group", "County", "Count Estimate", "Count Margin of Error", "Percent of Total Population", "Percent Margin of Error")
  
  names(age_county_dt) <- age_dt_county_names
  
  age_county_data_table <- datatable(age_county_dt, caption = "Table 1: Sullivan and Hawkins County, Tennessee Age Groups, 2018")
  
  age_county_data_table
  
  #kpt data table
  
  dt_age_kpt_counts_18 <- kpt_data_profile_18 %>%
    filter(variable %in% age_vars_18)
  
  dt_age_kpt_percent_18 <- kpt_data_profile_18 %>%
    filter(variable %in% age_vars_percent_18)
  
  age_kpt_df_18 <- cbind(age_col_dt_names_reg, dt_age_kpt_counts_18, dt_age_kpt_percent_18)

  age_kpt_dt_18 <- age_kpt_df_18[,c(1,5,6,12,13)]  

  #age_kpt_dt <- st_set_geometry(age_kpt_dt, NULL)  DONT NEED THIS BECAUSE THE SCHOOL DISTRICT DATA PULL DOESN"T SUPPORT LOCAITON DIRECTLY YET
  
  age_dt_kpt_names <- c("Age Group", "Count Estimate", "Count Margin of Error", "Percent of Total Population", "Percent Margin of Error")
  
  names(age_kpt_dt_18) <- age_dt_kpt_names  

  age_kpt_data_table_18 <- datatable(age_kpt_dt_18, caption = "Table 2: Kingsport, Tennessee Age Groups, 2018")
  
  age_kpt_data_table_18

```

## Map of Median Age

```{r median age map, echo = FALSE}

kpt_median_age <- kpt_data_profile_18 %>%
    filter(variable == "DP05_0018") %>%
    mutate(variable ="Median Age")
  
  kpt_joined_median_age <- full_join(kpt_18, kpt_median_age, by = "GEOID")
  
  
  trimmed_kpt_median_age <- kpt_joined_median_age[,c(15,17,18)]
  
  map_names_kpt_median_age <- c("Location", "Median Age", "Margin of Error", "geometry")
  
  names(trimmed_kpt_median_age) <- map_names_kpt_median_age
  
  
  
  median_age_county <- combined_county_dp_18 %>%
    filter(variable == "DP05_0018")
  
  
  trimmed_median_age_county <- median_age_county[,c(2,4,5)]
  
  map_names_county_median_age <- c("County", "Median Age", "Margin of Error", "geometry" )
  
  names(trimmed_median_age_county) <- map_names_county_median_age
  
  
  median_age_tract <- combined_tract_dp_18 %>%
    filter(variable == "DP05_0018")
  
  trimmed_median_age_tract <- median_age_tract[,c(2,4,5)]
  
  map_names_tract_median_age <- c("Census Tract", "Median Age", "Margin of Error", "geometry" )
  
  names(trimmed_median_age_tract) <- map_names_tract_median_age
  
  median_age_map <- mapview(list(trimmed_median_age_county, trimmed_median_age_tract, trimmed_kpt_median_age),
          zcol = list("Median Age", "Median Age", NULL),
          layer.name = list("Median Age County", "Median Age Tract", "Median Age City"),
          legend = list(FALSE, TRUE, FALSE))
  
  median_age_map

```

# Racial Demographics

```{r Racial Demographics, echo = FALSE}

####Racial demographics####
  
  race_vars_18 <- c("DP05_0063", "DP05_0064", "DP05_0065", "DP05_0066", "DP05_0067", "DP05_0068", "DP05_0069",
                 "DP05_0071")
  
  race_percent_vars_18 <- c("DP05_0063P", "DP05_0064P", "DP05_0065P", "DP05_0066P", "DP05_0067P", "DP05_0068P", "DP05_0069P", 
                        "DP05_0071P")
  
  race_vars_names_18 <- c("Total Population", "White", "African American", "American Indian or Alaskan Native",
                       "Asian", "Native Hawaiian or Pacific Island", "Some other Race", "Hispanic of Any Race")
  
  race_percent_names_18 <- c("Percent Total Population", "Percent White", "Percent African American", "Percent American Indian or Alaskan Native",
                          "Percent Asian", "Percent Native Hawaiian or Pacific Island", "Percent Some other Race", "Percent Hispanic of Any Race")
  
  df_race_tract_counts_18 <- combined_tract_dp_18 %>%
    filter(variable %in% race_vars_18)
  
  df_race_county_counts_18 <- combined_county_dp_18 %>%
    filter(variable %in% race_vars_18)
  
  df_race_tract_percent_18 <- combined_tract_dp_18 %>%
    filter(variable %in% race_percent_vars_18)
  
  df_race_county_percent_18 <- combined_county_dp_18 %>%
    filter(variable %in% race_percent_vars_18)
  
  df_race_kpt_counts_18 <- kpt_data_profile_18 %>%
    filter(variable %in% race_vars_18)
  
  df_race_kpt_percent_18 <- kpt_data_profile_18 %>%
    filter(variable %in% race_percent_vars_18)

  ##combine the percents into one table
  
  df_race_tract_18 <- cbind(race_vars_names_18, df_race_tract_counts_18, df_race_tract_percent_18)
  
  df_race_county_18 <- cbind(race_vars_names_18, df_race_county_counts_18, df_race_county_percent_18)
  
  df_race_kpt_18 <- cbind(race_vars_names_18, df_race_kpt_counts_18, df_race_kpt_percent_18)
  
      
      #adding location data in to this before trimming for mapping purposes, will remove a couple lines down but it 
      #makes sense to do this here
        
          #the names fucked up when cbind them together so rename them for some reason
        
      dummy_names <- names(df_race_county_18)
      
      dummy_names_2 <- dummy_names[-c(16,17)]
      
      names(df_race_kpt_18) <- dummy_names_2
      
      race_kpt_18_for_map <- left_join(kpt_18, df_race_kpt_18, by = "GEOID") #this has the location data
      
      
  
  trimmed_df_race_tract_18 <- df_race_tract_18[,c(1,3,5,6,12,13)] #these are the ones with the location data
  
  trimmed_df_race_county_18 <- df_race_county_18[,c(1,3,5,6,12,13)] #these are the ones with the location data
  
  trimmed_df_race_kpt_18 <- df_race_kpt_18[,c(1,5,6,12,13)] # no location data
  
  
  ##get ride of location data for the tract/county
  
  data_table_race_tract_18 <- st_set_geometry(trimmed_df_race_tract_18, NULL)
  
  data_table_race_county_18 <- st_set_geometry(trimmed_df_race_county_18, NULL)
  
  data_table_race_kpt_18 <- trimmed_df_race_kpt_18
  
  ##rename the columns 
  
  race_table_tract_names <- c("Racial Group", "Census Tract", "Count", "Margin of Error", "Percent", "Percent Margin of Error")
  
  race_table_county_names <- c("Racial Group", "County", "Count", "Margin of Error", "Percent", "Percent Margin of Error")  

  race_table_kpt_names <- c("Racial Group", "Count", "Margin of Error", "Percent", "Percent Margin of Error")
  
  names(data_table_race_tract_18) <- race_table_tract_names
  
  names(data_table_race_county_18) <- race_table_county_names
  
  names(data_table_race_kpt_18) <- race_table_kpt_names
  
  ##make the data tables
  
  race_tract_data_table_18 <- datatable(data_table_race_tract_18, caption = "Racial Breakdown of Census Tract Groups for Sullivan and Hawkins County, Tennessee 2018")
  
  race_county_data_table_18 <- datatable(data_table_race_county_18, caption = "Racial Breakdown for Sullivan and Hawkins County, Tennessee 2018")
  
  race_kpt_data_table_18 <- datatable(data_table_race_kpt_18, caption = "Racial Breakdown for Kingsport, Tennessee 2018")
  
  race_tract_data_table_18
  
  race_county_data_table_18
  
  race_kpt_data_table_18
  
  

```

## Percent White Population Map

```{r white people map, echo = FALSE}
###make a map of white
  
  race_tract_map_names <- c("Race", "Census Tract", "Count", "Count MOE", "Percent", "Percent MOE", "geometry")
  
  race_county_map_names <- c("Race", "County", "Count", "Count MOE", "Percent", "Percent MOE", "geometry")
  
  trimmed_race_kpt_18_for_map <- race_kpt_18_for_map[,c(15,16,18,19,25,26)]

  race_kpt_map_names <- c("Race", "Kingsport", "Count", "Count MOE", "Percent", "Percent MOE", "geometry")
  
  names(trimmed_df_race_county_18) <- race_county_map_names
  
  names(trimmed_df_race_tract_18) <- race_tract_map_names
  
  names(trimmed_race_kpt_18_for_map) <- race_kpt_map_names
  
  
  
  percent_white_county <- trimmed_df_race_county_18 %>%
    filter(Race == "White")
  
  
  percent_white_tract <- trimmed_df_race_tract_18 %>%
    filter(Race == "White")
  
  percent_white_kpt <- trimmed_race_kpt_18_for_map %>%
    filter(Race == "White")

  white_people_map <- mapview(list(percent_white_county,percent_white_tract, percent_white_kpt),
          zcol = list("Percent", "Percent", NULL),
          layer.name = list("Percent White County", "Percent White Tract", "Percent White City"),
          legend = list(FALSE, TRUE, FALSE))
  
  white_people_map
```

# Social Characteristics

```{r household characteristics, echo = FALSE}
household_vars_18 <- c("DP02_0001", "DP02_0002", "DP02_0003", "DP02_0004", "DP02_0007", "DP02_0009", "DP02_0012", "DP02_0013",
                         "DP02_0015", "DP02_0016", "DP02_0017", "DP02_0020", "DP02_0044", "DP02_0045", "DP02_0046", "DP02_0047",
                         "DP02_0048", "DP02_0050")
  
  household_percent_vars_18 <- c("DP02_0001P", "DP02_0002P", "DP02_0003P", "DP02_0004P", "DP02_0007P", "DP02_0009P", "DP02_0012P", "DP02_0013P",
                                 "DP02_0015P", "DP02_0016P", "DP02_0017P", "DP02_0020P", "DP02_0044P", "DP02_0045P", "DP02_0046P", "DP02_0047P",
                                 "DP02_0048P", "DP02_0050P")
  
  household_vars_names_18 <- c("Total Households", "Family Households", "Family Households with Children under 18", "Married Couple Family Households",
                               "Single Male Households with Children under 18", "Single Female Households with Children under 18", "Households of Age 65 or Greater Living Alone",
                               "Total Households with Children under 18", "Average Household Size", "Average Family Size", "Population in Households", "Children in Households", 
                               "Number of Grandparents Living With and Responsible for Children under 18 Years Old", "Number of Grandparents Living With and Responsible for Children under 1 Year Old",
                               "Number of Grandparents Living With and Responsible for Children 1-2 Years Old", "Number of Grandparents Living With and Responsible for Children 3-4 Years Old",
                               "Number of Grandparents Living With and Responsible for Children 5+ Years Old", "Number of Female Grandparents Living With and Responsible for Children under 18 Years Old")
  
  household_percent_varsnames_18 <- c("Percent Total Households", "Percent Family Households", "Percent of Family Households with Children under 18", "Percent Married Couple Family Households",
                                 "Percent Single Male Households with Children under 18", "Percent Single Female Households with Children under 18", "Percent Households of Age 65 or Greater Living Alone",
                                 "Percent Total Households with Children under 18", "Percent Average Household Size", "Percent Average Family Size", "Percent of Population in Households", "Percent of Children in Households", 
                                 "Percent Number of Grandparents Living With and Responsible for Children under 18 Years Old", "Percent of Number of Grandparents Living With and Responsible for Children under 1 Year Old",
                                 "Percent Number of Grandparents Living With and Responsible for Children 1-2 Years Old", " Percent of Number of Grandparents Living With and Responsible for Children 3-4 Years Old",
                                 "Percent of Number of Grandparents Living With and Responsible for Children 5+ Years Old", "Percent of Number of Female Grandparents Living With and Responsible for Children under 18 Years Old")
  
  
  df_household_tract_counts_18 <- combined_tract_dp_18 %>%
    filter(variable %in% household_vars_18)
  
  df_household_county_counts_18 <- combined_county_dp_18 %>%
    filter(variable %in% household_vars_18)
  
  df_household_tract_percent_18 <- combined_tract_dp_18 %>%
    filter(variable %in% household_percent_vars_18)
  
  df_household_county_percent_18 <- combined_county_dp_18 %>%
    filter(variable %in% household_percent_vars_18)
  
  df_household_kpt_counts_18 <- kpt_data_profile_18 %>%
    filter(variable %in% household_vars_18)
  
  df_household_kpt_percent_18 <- kpt_data_profile_18 %>%
    filter(variable %in% household_percent_vars_18)
  
  
  ##combine the percents into one table
  
  df_household_tract_18 <- cbind(household_vars_names_18, df_household_tract_counts_18, df_household_tract_percent_18)
  
  df_household_county_18 <- cbind(household_vars_names_18, df_household_county_counts_18, df_household_county_percent_18)
  
  df_household_kpt_18 <- cbind(household_vars_names_18, df_household_kpt_counts_18, df_household_kpt_percent_18)
  
  
  
  #adding location data in to this before trimming for mapping purposes, will remove a couple lines down but it 
  #makes sense to do this here
  
  #the names fucked up when cbind them together so rename them for some reason
  
  house_names <- names(df_household_county_18)
  
  house_names_2 <- house_names[-c(16,17)]
  
  names(df_household_kpt_18) <- house_names_2
  
  household_kpt_18_for_map <- left_join(kpt_18, df_household_kpt_18, by = "GEOID") #this has the location data
  
  
  
  trimmed_df_household_tract_18 <- df_household_tract_18[,c(1,3,5,6,12,13)] #these are the ones with the location data
  
  trimmed_df_household_county_18 <- df_household_county_18[,c(1,3,5,6,12,13)] #these are the ones with the location data
  
  trimmed_df_household_kpt_18 <- df_household_kpt_18[,c(1,5,6,12,13)] # no location data
  
  
  ##get ride of location data for the tract/county
  
  data_table_household_tract_18 <- st_set_geometry(trimmed_df_household_tract_18, NULL)
  
  data_table_household_county_18 <- st_set_geometry(trimmed_df_household_county_18, NULL)
  
  data_table_household_kpt_18 <- trimmed_df_household_kpt_18
  
  ##rename the columns 
  
  
  household_table_tract_names <- c("Household Measure", "Census Tract", "Count", "Margin of Error", "Percent", "Percent Margin of Error")
  
  household_table_county_names <- c("Household Measure", "County", "Count", "Margin of Error", "Percent", "Percent Margin of Error")  
  
  household_table_kpt_names <- c("Household Measure", "Count", "Margin of Error", "Percent", "Percent Margin of Error")
  
  names(data_table_household_tract_18) <- household_table_tract_names
  
  names(data_table_household_county_18) <- household_table_county_names
  
  names(data_table_household_kpt_18) <- household_table_kpt_names
  
  ##make the data tables
  
  household_tract_data_table_18 <- datatable(data_table_household_tract_18, caption = "Household Characteristics of Census Tract Groups for Sullivan and Hawkins County, Tennessee 2018")
  
  household_county_data_table_18 <- datatable(data_table_household_county_18, caption = "Household Characteristics for Sullivan and Hawkins County, Tennessee 2018")
  
  household_kpt_data_table_18 <- datatable(data_table_household_kpt_18, caption = "Household Characteristics for Kingsport, Tennessee 2018")
  
  household_tract_data_table_18  
  
  household_county_data_table_18
  
  household_kpt_data_table_18

```

```{r single mothers map, echo = FALSE}

 #single female household map
  
  
  
  household_tract_map_names <- c("Household Measure", "Census Tract", "Count", "Count MOE", "Percent", "Percent MOE", "geometry")
  
  household_county_map_names <- c("Household Measure", "County", "Count", "Count MOE", "Percent", "Percent MOE", "geometry")
  
  trimmed_household_kpt_18_for_map <- household_kpt_18_for_map[,c(15,16,18,19,25,26)]
  
  household_kpt_map_names <- c("Household Measure", "Kingsport", "Count", "Count MOE", "Percent", "Percent MOE", "geometry")
  
  names(trimmed_df_household_county_18) <- household_county_map_names
  
  names(trimmed_df_household_tract_18) <- household_tract_map_names
  
  names(trimmed_household_kpt_18_for_map) <- household_kpt_map_names
  
  
  percent_single_mothers_county <- trimmed_df_household_county_18 %>%
    filter(`Household Measure` == "Single Female Households with Children under 18")
  
  
  percent_single_mothers_tract <- trimmed_df_household_tract_18 %>%
    filter(`Household Measure` == "Single Female Households with Children under 18")
  
  percent_single_mothers_kpt <- trimmed_household_kpt_18_for_map %>%
    filter(`Household Measure` == "Single Female Households with Children under 18")
  
  single_mothers_map <- mapview(list(percent_single_mothers_county,percent_single_mothers_tract, percent_single_mothers_kpt),
                              zcol = list("Percent", "Percent", NULL),
                              layer.name = list("Percent Single Mothers County", "Percent Single Mothers Tract", "Percent Single Mothers City"),
                              legend = list(FALSE, TRUE, FALSE))
  single_mothers_map  


```

## References 

---
nocite: '@*'
...